---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
spec:
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: myapp
        image: coderpews/jenkins-plugin-scanner-backend:latest
        resources:
          requests:
            memory: "60Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: coderpews/jenkins-plugin-scanner-front:latest
        resources:
          requests:
            memory: "60Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: scanner
spec:
  type: ClusterIP
  selector:
    app: scanner
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - 34.76.55.153
  - scanner.demo.svc.cluster.local
  - front.demo.svc.cluster.local
  http:
  - name: "api"
    match:
    - uri:
        prefix: "/api/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: scanner
  - name: "frontend"
    match:
    - uri:
        prefix: "/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: front