kind: Service
apiVersion: v1
metadata:
  name:  jenkins-plugin-scanner
spec:
  selector:
    app:  jenkins-plugin-scanner
  type:  ClusterIP
  ports:
  - name:  web
    port:  80
    targetPort:  5000